logging:
  level:
    com.stronans.domotics: DEBUG

management:
  context-path: /domotic/api/

server:
  port: 31000

com:
  stronans:
    domotics:
      host: localhost
      port: 3306
      dbName: domotics
      userName: measure
      userPassword: measure
