application:
  title: Domotics
  version: @pom.version@

# Log4j2 configuration
logging:
  file: logs/logging.log
  pattern:
#    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    com.stronans.domotics: DEBUG

# Spring actuator endpoints
management:
  context-path: /domotic/api/
  security:
    enabled: false

# Tomcat public facing port for all uri
server:
  port: 31000

# Application specific properties
com:
  stronans:
    domotics:
      host: 192.168.1.50
      port: 8529
      dbName: domotics
      userName: measure
      userPassword: measure


#      host: 192.168.1.50

build:
  version: @pom.version@
  date: @timestamp@

caching:
  specs:
    - cacheName: stationList
      maxsize: 10
      ttl: 10h
    - cacheName: sensorList
      maxsize: 10
      ttl: 10h
