-- MySQL Script generated by MySQL Workbench
-- 07/09/16 15:43:14
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema domotics
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `domotics` ;

-- -----------------------------------------------------
-- Schema domotics
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `domotics` DEFAULT CHARACTER SET utf8 ;
USE `domotics` ;

-- -----------------------------------------------------
-- Table `domotics`.`temperature`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `domotics`.`temperature` ;

CREATE TABLE IF NOT EXISTS `domotics`.`temperature` (
  `idtemperature` BIGINT(30) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Incremental unique key for this table.',
  `stationId` INT NULL COMMENT 'Which station produced this reading/measument',
  `value` DOUBLE NULL COMMENT 'temperature value',
  `timestamp` TIMESTAMP NULL COMMENT 'timestamp when reading received.',
  PRIMARY KEY (`idtemperature`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idtemperature_UNIQUE` ON `domotics`.`temperature` (`idtemperature` ASC);


-- -----------------------------------------------------
-- Table `domotics`.`stations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `domotics`.`stations` ;

CREATE TABLE IF NOT EXISTS `domotics`.`stations` (
  `id` INT NOT NULL,
  `stationName` VARCHAR(45) NULL,
  `stationDescription` VARCHAR(2000) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `domotics`.`humidity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `domotics`.`humidity` ;

CREATE TABLE IF NOT EXISTS `domotics`.`humidity` (
  `idhumidity` BIGINT(30) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Incremental unique key for this table.',
  `stationId` INT NULL COMMENT 'Which station produced this reading/measument',
  `value` DOUBLE NULL COMMENT 'humidity value',
  `timestamp` TIMESTAMP NULL COMMENT 'timestamp when reading received.',
  PRIMARY KEY (`idhumidity`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idtemperature_UNIQUE` ON `domotics`.`humidity` (`idhumidity` ASC);


-- -----------------------------------------------------
-- Table `domotics`.`heatindex`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `domotics`.`heatindex` ;

CREATE TABLE IF NOT EXISTS `domotics`.`heatindex` (
  `idheatindex` BIGINT(30) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Incremental unique key for this table.',
  `stationId` INT NULL COMMENT 'Which station produced this reading/measument',
  `value` DOUBLE NULL COMMENT 'Heat Index value',
  `timestamp` TIMESTAMP NULL COMMENT 'timestamp when reading received.',
  PRIMARY KEY (`idheatindex`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idtemperature_UNIQUE` ON `domotics`.`heatindex` (`idheatindex` ASC);

SET SQL_MODE = '';
GRANT USAGE ON *.* TO measure;
 DROP USER measure;
SET SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';
CREATE USER 'measure' IDENTIFIED BY 'measure';

GRANT SELECT, INSERT, TRIGGER ON TABLE `domotics`.* TO 'measure';
GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `domotics`.* TO 'measure';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
